//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogFileVisualizerLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogFileVisualizerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogFileVisualizerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogFileVisualizerLib.LogFileVisualizerResources", typeof(LogFileVisualizerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @version varchar(50) = cast(serverproperty(&apos;ProductVersion&apos;) as varchar(50));
        ///declare @dotPosition int = charindex(&apos;.&apos;, @version);
        ///declare @majorVersion int = case when @dotPosition &gt; 0 then cast(substring(@version, 1, @dotPosition - 1) as int) end;
        ///
        ///if object_id(&apos;tempdb.dbo.#loginfo&apos;) is not null
        ///	drop table #loginfo;
        ///create table #loginfo
        ///(
        ///	DummyColumn int
        ///);
        ///
        ///if @majorVersion &gt;= 11 -- SQL Server 2012 or higher.
        ///begin
        ///	alter table #loginfo
        ///	add RecoveryUnitId int;
        ///end
        ///
        ///alter tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DbccLoginfo {
            get {
                return ResourceManager.GetString("DbccLoginfo", resourceCulture);
            }
        }
    }
}
